<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
</head>
<body>
<?php if ( isset($student) ) : ?>
    <h1 style="text-align: center">Administration page</h1>
    <?php
    $isAdmin = false;
    foreach ($student->roles as &$role) {
        if ($role->role == 'Admin') {
            $isAdmin = true;
        }
    }?>
    <?php if ($isAdmin == true) : ?>
        <h2 style="text-align: center; background-color: green"> Hello, administrator </h2>




    <?php else: ?>
        <h2 style="text-align: center; background-color: red"> You are not an administrator </h2>
    <?php endif; ?>
<?php endif; ?>
</body>
</html>
