<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
</head>
<?php require '../templates/component/session_header.php'?>
<body>
<?php if ( isset($student) ) : ?>
    <h1 style="text-align: center">Administration page</h1>
    <?php if ($student->isAdmin()) : ?>
        <?php if ( isset($pastries) ) : ?>
            <h2 style="text-align: center">Pastry management</h2>

            <table style="margin-left:auto;margin-right:auto;">
                <?php foreach ($pastries as &$pastry) { ?>
                    <tr>
                        <td>
                            <?= $pastry->name?>
                        </td>
                    </tr>
                <?php } ?>

                <tr>
                    <form method="post">
                        <td>
                            <input type="text" name="newPastry" required>
                        </td>
                        <td>
                            <input type="submit" value="addPastry">
                        </td>
                    </form>
                </tr>
            </table>
            <hr>
        <?php endif; ?>

        <?php if (isset($allStudent)) : ?>
            <h2 style="text-align: center">Student right management</h2>

            <table style="margin-left:auto;margin-right:auto;">
                <?php foreach ($allStudent as &$st) { ?>
                    <tr>
                        <td>
                            <?= $st->login?>
                        </td>
                        <td>
                            <?php if ($st->id == $student->id) :?>
                                <b>You</b>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php foreach ($st->roles as &$role) { ?>
                        <tr>
                            <td></td>
                            <td>
                                <?= $role->role ?>
                            </td>
                            <td>
                                <form method="post">
                                    <input type="text" name="role" value="<?= $role->id ?>" hidden>
                                    <input type="submit" name="editRole" value="remove">
                                </form>
                            </td>
                        </tr>
                    <?php } ?>
                    <?php if (!($st->isAdmin() && $st->isDelegue() && $st->isBDE())) : ?>
                        <tr>
                            <td></td>
                            <form method="post">
                                <td>
                                    <select name="roleValue">
                                        <?php if (!$st->isAdmin()) :?>
                                            <option>Admin</option>
                                        <?php endif; ?>
                                        <?php if (!$st->isBDE()) :?>
                                            <option>BDE</option>
                                        <?php endif; ?>
                                        <?php if (!$st->isDelegue()) :?>
                                            <option>Delegue</option>
                                        <?php endif; ?>
                                    </select>
                                </td>
                                <td>
                                    <input type="text" name="idStudent" value="<?= $st->id ?>" hidden>
                                    <input type="submit" value="add" name="editRole">
                                </td>
                            </form>
                        </tr>
                    <?php endif; ?>
                <?php } ?>
            </table>
        <?php endif; ?>
    <?php else: ?>
        <h2 style="text-align: center; background-color: red"> You are not an administrator </h2>
    <?php endif; ?>
<?php endif; ?>
</body>
</html>
