<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Index</title>
</head>
<body>

<h1 style="text-align:center">Login / Register</h1>

<form style="text-align:center" action="/" method="post">
    <h2>Login</h2>
    <table style="margin-left:auto;margin-right:auto;">
        <tr>
            <td>
                <h3>Login</h3>
            </td>
            <td>
                <label>
                    <input type="text" name="login" placeholder="ex: Luffy" pattern="[A-Za-z0-9]+" required>
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Password</h3>
            </td>
            <td>
                <label>
                    <input  type="password" name="password" placeholder="ex: *****" pattern="[A-Za-z0-9]+" required>
                </label>
            </td>
        </tr>
    </table>
    <input type="submit" name="submit" value="Login"/>
</form>
<?php if (isset($loginError)) : ?>
    <p style="background-color: indianred; text-align: center">
        Error while tying to login : Bad login or password
    </p>
<?php endif; ?>

<hr>

<form style="text-align:center" action="/" method="post">
    <h2>Register</h2>


    <table style="margin-left:auto;margin-right:auto;">
        <tr>
            <td>
                <h3>Login</h3>
            </td>
            <td>
                <label>
                    <input type="text" name="login" placeholder="ex: Luffy" pattern="[A-Za-z0-9]+" required>
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Alias</h3>
            </td>
            <td>
                <label>
                    <input type="text" name="alias" placeholder="ex: Straw hat" pattern="[A-Za-z0-9]+" required>
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Password</h3>
            </td>
            <td>
                <label>
                    <input name="password" type="password" placeholder="ex: ******" pattern="[A-Za-z0-9]+" required>
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Favorite pastry</h3>
            </td>
            <td>
                <label>
                    <select name="pastry">
                        <option value="">--Please choose a favorite pastry--</option>
                        <?php if (isset($pastries)) : ?>
                            <?php foreach ($pastries as $pastry) {?>
                                <option value="<?= $pastry->id ?>"><?= $pastry->name ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </label>
            </td>
        </tr>
    </table>
    <input type="submit" name="submit" value="Register"/>
</form>

<?php if (isset($registerError)) : ?>
<?php if ($registerError) : ?>
    <p style="background-color: darkgreen; text-align: center">
        Student successfully registered
    </p>
<?php else : ?>
    <p style="background-color: indianred; text-align: center">
        Error while registering: Student already exist
    </p>
<?php endif; ?>
<?php endif; ?>
</body>
</html>
