<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
</head>
<body>

<h1>Login / Register</h1>

<h2>Login</h2>

<form action="/" method="post">
    <label>
        <h3>
            Login
            <input type="text" name="login">
        </h3>
    </label>

    <label>
        <h3>
            Password
            <input type="text" name="password">
        </h3>
    </label>

    <input type="submit" name="submit" value="Login"/>
</form>

<hr>

<h2>Register</h2>

<label>
    <h3>
        Login
        <input type="text">
    </h3>
</label>

<label>
    <h3>
        Alias
        <input type="text">
    </h3>
</label>

<label>
    <h3>
        Password
        <input type="text">
    </h3>
</label>

<label>
    <h3>
        Favorite pastry
        <select name="pastry" id="pastry-select">
            <option value="">--Please choose a favorite pastry--</option>
            <?php if (isset($pastries)) : ?>
                <?php foreach ($pastries as $pastry) {?>
                    <option value="<?= $pastry->name ?>"><?= $pastry->name ?></option>
                <?php } ?>
            <?php endif; ?>
        </select>
    </h3>
</label>

<button>Register</button>

</body>
</html>
