<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Index</title>
</head>
<body>

<h1 style="text-align:center">Login / Register</h1>

<form style="text-align:center" action="/" method="post">
    <h2>Login</h2>
    <table style="margin-left:auto;margin-right:auto;">
        <tr>
            <td>
                <h3>Login</h3>
            </td>
            <td>
                <label>
                    <input type="text" name="login">
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Password</h3>
            </td>
            <td>
                <label>
                    <input  type="password" name="password">
                </label>
            </td>
        </tr>
    </table>
    <input type="submit" name="submit" value="Login"/>
</form>

<hr>

<form style="text-align:center" action="/" method="post">
    <h2>Register</h2>


    <table style="margin-left:auto;margin-right:auto;">
        <tr>
            <td>
                <h3>Login</h3>
            </td>
            <td>
                <label>
                    <input type="text" name="login">
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Alias</h3>
            </td>
            <td>
                <label>
                    <input type="text" name="alias">
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Password</h3>
            </td>
            <td>
                <label>
                    <input name="password" type="password">
                </label>
            </td>
        </tr>
        <tr>
            <td>
                <h3>Favorite pastry</h3>
            </td>
            <td>
                <label>
                    <select name="pastry">
                        <option value="">--Please choose a favorite pastry--</option>
                        <?php if (isset($pastries)) : ?>
                            <?php foreach ($pastries as $pastry) {?>
                                <option value="<?= $pastry->name ?>"><?= $pastry->name ?></option>
                            <?php } ?>
                        <?php endif; ?>
                    </select>
                </label>
            </td>
        </tr>
    </table>
    <input type="submit" name="submit" value="Register"/>
</form>

<p style="background-color: red; text-align: center">
    Error while registering: Student already existe
</p>

</body>
</html>
